import type { Metadata } from "next";
import { Header, Footer } from "./components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    {
      href: "/",
      name: "Home",
    },
    {
      href: "/about",
      name: "About"
    },
    {
      href: "/portfolio",
      name: "Portfolio"
    },
    {
      href: "/resume",
      name: "Resume"
    },
    {
      href: "/blog",
      name: "Blog"
    },
    {
      href: "/contact",
      name: "Contact"
    }
  ];

  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
        <Header navLinks={navLinks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
