import type { Metadata } from "next";
import { robotoCondense } from "./components/fonts";
import "./globals.css";
import AppNavbar from "./components/AppNavbar";
import AppFooter from "./components/AppFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondense.className } antialiased flex flex-col min-h-screen`}
      >
        <AppNavbar />
        <main className="flex grow">
          {children}
        </main>
        <AppFooter />
      </body>
    </html>
  );
}
