import type { Metadata } from "next";
import { Header, Footer } from "./components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    {
      href: "/",
      name: "Home",
    },
    {
      href: "/about",
      name: "About"
    },
    {
      href: "/work",
      name: "Work"
    },
    // {
    //   href: "/resume",
    //   name: "Resume"
    // },
    // {
    //   href: "/blog",
    //   name: "Blog"
    // },
    {
      href: "/contact",
      name: "Contact"
    }
  ];

  return (
    <html lang="en">
      <body
        className={"antialiased min-h-screen flex flex-col"}
      >
        <Header navLinks={navLinks} />
        <div className="flex-grow">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
